version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kz8v4h2ujk6b"
s3_prefix = "sam-app"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
