name: Lambda Deploy
on:
  push:
    branches:
      - main
    paths:
      - sam-symployees/**
  workflow_dispatch:
jobs:
  tests:
    name: Tests 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install requirements
        run: |
          pip install -r sam-symployees/app/requirements.txt
      - name: Start tests
        run: |
          pytest sam-symployees/tests/*
  # build:
  #   name: Build lambda package
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3
  #     - name: Install SAM 
  #       uses: aws-actions/setup-sam@v2
  #       with:
  #         version: 1.23.0
  #     - uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.region }}
  #     - name: SAM Build
  #       run: sam build
      
      
      