name: Lambda Deploy
on:
  push:
    branches:
      - main
    paths:
      - sam-symployees/**
  workflow_dispatch:
env:
  AWS_REGION: eu-central-1
jobs:
  tests:
    name: Tests 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install requirements
        run: |
          pip install -r sam-symployees/app/requirements.txt
      - name: Start tests
        run: |
          pytest sam-symployees/tests/*
  build-and-deploy:
    name: Build and deploy lambda function
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install SAM 
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.23.0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: SAM Build
        run: |
          cd sam-symployees && sam build
      - name: Zip package
        id: build-lambda
        run: |
          apt install zip
          cd sam-symployees/.aws-sam/build/ImportEmployeesLambda/ && zip lambda-$(date +'%d-%m-%y').zip app.py
          echo "lambda_pkg_name=$(lambda-$(date +'%d-%m-%y'))" >> $GITHUB_OUTPUT
      - name: Deploy lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: dev-import-employees
          zip_file: ${{ steps.build-lambda.outputs.lambda_pkg_name }}