name: manual-approval

on:
    push:
        branches: ["main"]
        paths:
            - manual-approval/**
    pull_request:
        branches: ["main"]
        paths:
            - manual-approval/**

env:
    BUILD_NUMBER: ${{ github.run_number }}

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci
                working-directory: './manual-approval'

            - name: Build app
              run: npm run build
                working-directory: './manual-approval'

            - name: Run tests
              run: npm run test:ci -- -u
                working-directory: './manual-approval'

            # Upload Artifact
            - name: Upload built files
              uses: actions/upload-artifact@v3
              with:
                  name: "build-artifact-${{ env.BUILD_NUMBER }}"
                  path: ./.next
                  if-no-files-found: error
                  retention-days: 90

            - uses: trstringer/manual-approval@v1
              with:
                  secret: ${{ github.TOKEN }}
                  approvers: symphony-srdjan,bnikolic-symphony,irekovic,ivan-herceg-symphony,nikolasymph,slavisa-radicevic
                  minimum-approvals: 1
                  issue-title: "Approve deploy to dev for build version ${{ env.BUILD_NUMBER }}"
                  exclude-workflow-initiator-as-approver: false
    deploy-to-dev:
        name: Deploy to dev
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download built files
              uses: actions/download-artifact@v3
              with:
                  name: "build-artifact-${{ env.BUILD_NUMBER }}"
                  path: ./.next

            - name: Deploy to dev
              run: "echo 'Deploying to dev'"

            - uses: trstringer/manual-approval@v1
              with:
                  secret: ${{ github.TOKEN }}
                  approvers: symphony-srdjan,bnikolic-symphony,irekovic,ivan-herceg-symphony,nikolasymph,slavisa-radicevic
                  minimum-approvals: 1
                  issue-title: "Approve deploy to QA for build version ${{ env.BUILD_NUMBER }}"
                  exclude-workflow-initiator-as-approver: false
    deploy-to-qa:
        name: Deploy to QA
        needs: deploy-to-dev
        runs-on: ubuntu-latest
        steps:
            - name: Download built files
              uses: actions/download-artifact@v3
              with:
                  name: "build-artifact-${{ env.BUILD_NUMBER }}"
                  path: ./.next
            - name: Deploy to QA
              run: "echo 'Deploying to QA'"
            - uses: trstringer/manual-approval@v1
              with:
                  secret: ${{ github.TOKEN }}
                  approvers: symphony-srdjan,bnikolic-symphony,irekovic,ivan-herceg-symphony,nikolasymph,slavisa-radicevic
                  minimum-approvals: 1
                  issue-title: "Approve deploy to prod for build version ${{ env.BUILD_NUMBER }}"
                  exclude-workflow-initiator-as-approver: false
    deploy-to-prod:
        name: Deploy to prod
        needs: deploy-to-qa
        runs-on: ubuntu-latest
        steps:
            - name: Download built files
              uses: actions/download-artifact@v3
              with:
                  name: "build-artifact-${{ env.BUILD_NUMBER }}"
                  path: ./.next
            - name: Deploy to prod
              run: "echo 'Deploying to prod'"
